version: "3.9"

services:
  backend:
    build:
      context: ./backend
    environment:
      - PORT=3001
      - SERVER_FRONTEND_URL=${SERVER_FRONTEND_URL:-http://localhost:3000}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - backend_data:/app/data

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL:-http://localhost:3001}
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL:-http://localhost:3001}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: instantly-ai-network

volumes:
  backend_data:


